---
apiVersion: v1
kind: ReplicationController
metadata:
  name: flm
spec:
  replicas: 2
  selector:
    app: swiggy
  template:
    metadata:
      name: mytemp
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/paytm:movie
          ports:
            - containerPort: 80
